### ISSUE TITLE
no method 'show', no method 'hide'

### ISSUE THREAD

**Issue by ghost** [ksylvest/jquery-spin#1]
1. clone the repository to your local system
   open up index.html

open chrome developer tools and run the following script commands

$('.spinner').spinner();
[
<div class=​"spinner" data-spinner>​
​</div>​
]
$('.spinner').spinner('show');
TypeError: Object has no method 'show'
$('.spinner').spinner('hide');
TypeError: Object has no method 'hide'

observe:
TypeError: Object has no method 'show'
TypeError: Object has no method 'hide'

**Comment by ksylvest** [comment]
A hosted version of the 'index.html' file exists at the following URL: http://ksylvest.github.io/jquery-spinner/

Running the following on that URL (as well as on my local clone of the project) worked fine:

```
$('.spinner').spinner();
$('.spinner').spinner('show');
$('.spinner').spinner('hide');
```

I'm closing. If you have better repro steps or still can't get it working please comment and we can re-open.
